// Code generated by mockery v1.1.0. DO NOT EDIT.

package custom

import (
	mock "github.com/stretchr/testify/mock"
	cli "gitlab.com/gitlab-org/ci-cd/custom-executor-drivers/fargate/internal/cli"
)

// mockCustomCommand is an autogenerated mock type for the customCommand type
type mockCustomCommand struct {
	mock.Mock
}

// CustomExecute provides a mock function with given fields: ctx
func (_m *mockCustomCommand) CustomExecute(ctx *cli.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cli.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
