// Code generated by mockery v1.1.0. DO NOT EDIT.

package task

import mock "github.com/stretchr/testify/mock"

// MockMetadataManager is an autogenerated mock type for the MetadataManager type
type MockMetadataManager struct {
	mock.Mock
}

// Clear provides a mock function with given fields:
func (_m *MockMetadataManager) Clear() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *MockMetadataManager) Get() (Data, error) {
	ret := _m.Called()

	var r0 Data
	if rf, ok := ret.Get(0).(func() Data); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Data)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Persist provides a mock function with given fields: data
func (_m *MockMetadataManager) Persist(data Data) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(Data) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
