// Code generated by mockery v1.1.0. DO NOT EDIT.

package encoding

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockEncoder is an autogenerated mock type for the Encoder type
type MockEncoder struct {
	mock.Mock
}

// Decode provides a mock function with given fields: source, target
func (_m *MockEncoder) Decode(source io.Reader, target interface{}) error {
	ret := _m.Called(source, target)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(source, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encode provides a mock function with given fields: source, target
func (_m *MockEncoder) Encode(source interface{}, target io.Writer) error {
	ret := _m.Called(source, target)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, io.Writer) error); ok {
		r0 = rf(source, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
