// Code generated by mockery v1.1.0. DO NOT EDIT.

package executors

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, connection, script
func (_m *MockExecutor) Execute(ctx context.Context, connection ConnectionSettings, script []byte) error {
	ret := _m.Called(ctx, connection, script)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ConnectionSettings, []byte) error); ok {
		r0 = rf(ctx, connection, script)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
