// Code generated by mockery v1.1.0. DO NOT EDIT.

package ssh

import mock "github.com/stretchr/testify/mock"

// MockKeyFactory is an autogenerated mock type for the KeyFactory type
type MockKeyFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: bitSize
func (_m *MockKeyFactory) Create(bitSize int) (*KeyPair, error) {
	ret := _m.Called(bitSize)

	var r0 *KeyPair
	if rf, ok := ret.Get(0).(func(int) *KeyPair); ok {
		r0 = rf(bitSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*KeyPair)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(bitSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
